### ISSUE TITLE
Slicers display only first 100 records

### ISSUE THREAD

**Issue by Tibor999** [MattWade-MS/QER#1]
Using a standard slicer e.g. to select the Second Network Name, I get only first 100 locations, the rest is not displayed.
There are all of them, when I switch the visual to table
Using the slicer with another source like excel, I get all the lines visible
This behavior is the same in PowerBI Desktop and Service

**Comment by Tibor999** [comment]
This issue is active in v4.3 too, you can check it in page Dailies, slicers Building Name or City

**Comment by ViValentin** [comment]
Hello,
Same issue on our side.
I can have more locations within the filter of the visual by lazy loading but it seems the slicer doesn't have lazy loading.
I don't known if it is a limitation of the visual itself (and so in all PowerBI report using this visual) or it is specific to this report.
Thanks for help
Regards

**Comment by MattWade-MS** [comment]
The slicer is limited to only 100 entries.  This is a limitation of Power BI, not the template or CQD.  To address this you can use the search function of a slicer.  To get the search to work you need to append a wildcard character.  IE: Swi* will return all results with swi in the name.  I've had limited success with this and Direct Query as sometimes it works perfectly, other times I have to add more characters like swis*.

**Comment by ViValentin** [comment]
Hello MattWade,
Thank for explanation. I have tested and it works.
I think we can close this non issue
Regards

**Comment by Tibor999** [comment]
Hello Matt,

unfortunatelly the search functionality in this slicer does not work for me, even when I enter whole name.
Looks like it's caused by huge data  (669 colums with some tens of millions records). 
There is no such limit in standard slicer - when you create new table with column {1..1000}, all rows are displayed in a slicer, both list or dropdown.
Whole issue is caused by datasource from custom connector, that is joining multiple tables in one huge, that can not be handled the standard way. 
Is there some possibility for us to edit that custom connector and at least to remove unused columns please?

**Comment by MattWade-MS** [comment]
At this time it is not possible to edit the custom connector.  We are working on eliminating the need for the SDK based connector by rewriting it in PBI native code and I hope to see something later this CY.  This will hopefully address the issue or at least make the slicer more predictable.  The challenge here is that we rely on Direct Query mode and this changes how PBI behaves.
