### ISSUE TITLE
Charts and tables are blank on Transport page with VDI filter

### ISSUE THREAD

**Issue by bjlarock** [MattWade-MS/QER#10]
Hi, 

When attempting to filter on the Transport page, and using Client Microsoft Teams Citrix VDI, none of the charts render (most of the time no error). This occurred with 4.4 and 4.5, as well as with the published dashboard on PBIO. 

![image](https://user-images.githubusercontent.com/99736865/154069696-12e197ae-eef8-4d23-8f69-b012bf59a327.png)

**Comment by MattWade-MS** [comment]
This is a known issue with VDI telemetry.  VDI endpoints are not reporting transport type and thus, when you try to filter on VDI you get blank reports because there is no transport data.  We are working hard to address the telemetry gap in VDI.

**Comment by bjlarock** [comment]
Hi Matt - wanted to follow up on this. do you have any suggestions on how to filter the data down to our virtual environment?

Thanks!
Brian

**Comment by MattWade-MS** [comment]
We are working on this right now and expect to have some new VDI based dimension in CQD by the end of Q1 2023 (targeted but likely to achieve).  Once these new dimensions are in place you'll be able to filter out (or focus on) VDI endpoints.
