### ISSUE TITLE
Predefined time windows

### ISSUE THREAD

**Issue by Petri-X** [MattWade-MS/QER#11]
Hi,
When I take a look the rate my calls I realizing that suddenly we have started to receive lot of rate my call surveys. When I tried to deep diver to these I was limiting the number of days to today only:
![image](https://user-images.githubusercontent.com/43988151/157213290-3064e07d-2763-4f73-be77-b1c5fd2b3c2e.png)
But when I was looking for one user I noticed that she has made 10 surveys today, and all of them were poor. When I take a look user's calls I found only one call from her.

So question is, if I'm limiting the timespan to one day, should that impact to also to those which have subject with: "28 days" or "90 days" etc.. Or do you know how one user could have 10 surveys with only one call. Based on the CDR she did not had multiple calls to that meeting.

**Comment by MattWade-MS** [comment]
Thank you for bringing this to my attention.  I will take a look at the report and see if there is an issue.
