### ISSUE TITLE
QER 4.5 Color Thresholds

### ISSUE THREAD

**Issue by Briggidy** [MattWade-MS/QER#12]
New thresholds are showing multiple colors vs just green/yellow/red from previous versions.   I am also told there are orange and lighter shades of red.  Folks who are colorblind may have issues with this.  Can you provide the thresholds you are using in a chart or when getting the popup from the value have a (low/medium/high) type after the value if possible.

**Comment by MattWade-MS** [comment]
Thank you Briggidy.  I'm actually working on improving colors here for those that have difficulty with color vision.  In the "heat map" based visuals, I use a 3-color gradient scale and the thresholds are provided in the visual itself by reviewing the Conditional Formatting of the Background color.  Heat maps have a gradient scale and single metric visuals (like a card) have a rule-based scale.

I'll look into documenting them in a spreadsheet or something like that for future release.
