### ISSUE TITLE
"Bandwidth Est" dimension

### ISSUE THREAD

**Issue by krugerd** [MattWade-MS/QER#13]
Hello - first, this QERPBI template/report is amazing.  Very good work here!

Not necessarily an issue, but I was looking for more information on the "Bandwidth Est" dimension shown on the Call Health Details and Meeting Health Details tabs.  The only documentation I can find on this dimension is:
Average estimated bandwidth available between first and second endpoint in bits per second.Example value: 026: [260000 - 270000)
The reported data I am seeing in the report does not seem to match up with Media Bit Rate settings in use in our tenant. 

I am able to determine the effective Media Bit Rate in use on a Teams Desktop client (Windows, Mac and Linux).  However, I am working with Microsoft to try and determine this clearly on non-desktop clients (Mobile IOS, Mobile Android, Teams Android Devices, Citrix VDI clients, browser, etc.)  I have been advised to refer to this measurement in the Call Quality Dashboard.  

However I don't believe this shows me the same thing.  Is this referring to "potential" or "available" bandwidth between two endpoints (per stream, per user, per direction)?  what exactly is this showing?  Should this be close to the reported data in the "Call Health Details" panel in the Teams client (updated every 15s?)  And if it is in bps, would the example above of 026: (260000 - 270000) mean 260000bps average for the duration of that stream?

We are trying to clearly determine the effective Media Bit Rate in use on a device.  With desktop client logs, we can determine what roaming bandwidth policy was applied to the device, and what the actual applied MediaBitRateKb is.  But this is not as simple with the non-desktop clients so hoping to find this somewhere in the CQD

Thank you

**Comment by krugerd** [comment]
@MattWade-MS

**Comment by MattWade-MS** [comment]
Estimated BW is just that, the client is estimating the available BW at the onset of the call.  It has no relation to the media bit rate value. CQD does not contain a value of actual BW usage as CQD deals in aggregated data.  I might suggest you take a peak at this GitHub report a colleague of mine created to help answer return to office scenarios.

https://github.com/TeamsHackbox/BandwidthEstimation/blob/main/Concurrency%20-%20Back2Office-%20v1.5.pbix

**Comment by krugerd** [comment]
Thanks for the link and explanation of the dimension.  This makes sense.  My issue was that the information I received from support to be able to determine media bit rate for non-desktop clients was in the CQD (QER PBI report).  Confirmed now this is not the case.  Thanks.
