### ISSUE TITLE
incorrect data showing when adding new tab and creating table visualization

### ISSUE THREAD

**Issue by krugerd** [MattWade-MS/QER#15]
(using latest Power BI desktop and QER PBI 4.7 template).

Clicked to add new tab to report, and added a few measures as columns.  Date, First UPN, Second UPN, First Building Name, Second Building Name, First Inside Corp, Second Inside Corp, Inside Corp Pair  (it doesnt seem to matter after adding a few columns it seems to happen - I am trying to create a report showing users (UPNs) making, receiving P2P and Conf calls inside our buildings only.

Then when adding or removing measures (columns), the display ends up showing the information from the wrong measure (column).   For example, the date shows under the Conf ID column, or Inside Corp info shows under the UPN column.

Refreshing data doesnt seem to fix it.  Removing columns just moves the data to different columns.  
See below:
![odd](https://user-images.githubusercontent.com/99920431/183493836-7bfaa246-dcbf-42a2-ac0a-fc1dde70eeb7.JPG)

**Comment by MattWade-MS** [comment]
Please make sure your query has both a dimension and a measure.  I do not see a measure in your query.  Please see a list measures here:  https://docs.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard#measurements

**Comment by krugerd** [comment]
I have a support case open with Microsoft and will be commenting thru that.  Thanks Matt.
