### ISSUE TITLE
Overall PSTN Health (Last 28Days) - Not Labelling Operator Connect calls.

### ISSUE THREAD

**Issue by lewisd79** [MattWade-MS/QER#17]
Hi, 

I am checking the QER v4.7 and noted that the Overall PSTN Health (Last 28 days) page isn't labelling Operator Connect calls. They are showing as 'Unknown'. We use Operator Connect, so I know these are valid calls. See below:

![Operator Connect calls as Unknown](https://user-images.githubusercontent.com/89141201/188183052-6e76fae0-1b00-4afc-b8e8-bf0284802b4e.jpg)

Is there a way to alert this? 

Thanks, 

Damian

**Comment by MattWade-MS** [comment]
Yes, this is a known issue.  I am working with the CQD team to get a new value added here for Operator Connect.
