### ISSUE TITLE
P2P calls in search - Need to search by the 2nd UPN

### ISSUE THREAD

**Issue by lewisd79** [MattWade-MS/QER#18]
Hi 

To find a P2P call that I started, I need to search for the person that I dialed to find the call. This is because the 'Search for a User' filter is the 'Second UPN' Field. See below. 

Call Health Details for the P2P call. 
![Call Health Details](https://user-images.githubusercontent.com/89141201/188478188-82e83fb3-e874-4802-9471-eefa8ab1d22d.jpg)

Search page for 1st UPN.
![Search page 1st UPN](https://user-images.githubusercontent.com/89141201/188478588-7a1d6db9-39ca-4ba7-baf7-b3b1985d66db.jpg)

Search page for 2nd UPN.
![Search page 2nd UPN](https://user-images.githubusercontent.com/89141201/188478622-0071ba42-5d7a-4cba-8315-cb72f637d50e.jpg)

For P2P calls, would it make sence to search by the 1st UPN? 

Thanks, 

Damian

**Comment by MattWade-MS** [comment]
Good feedback.  CQD treats VOIP and PSTN calls differently (much to my dismay) so it's difficult given the current limitations of the connector and direct query.  I will look into this more to see if there are ways to search first and/or second more easily.
