### ISSUE TITLE
Access to the resource is forbidden

### ISSUE THREAD

**Issue by frederick-mendoza** [MattWade-MS/QER#3]
We are getting an error when launching/syncing the QER dashboard

We have tested this on different PC's, different networks and with the updated QER versions.

We have raised this concern to Microsoft Premier Support but they have advised us to open this ticket from here as the template was provided from GitHub team.

![QER Issue](https://user-images.githubusercontent.com/88764121/130055308-9c2bff04-a3de-4b5b-a1a6-c710e5804565.png)

**Comment by simon-modality** [comment]
Has that account got a role that gives CQD access, and if you use PIM is that role currently activated?

Need Teams Communications Support Engineer or better.  https://docs.microsoft.com/en-us/microsoftteams/turning-on-and-using-call-quality-dashboard#assign-admin-roles-for-access-to-cqd

**Comment by frederick-mendoza** [comment]
Dear Team,

                Yes, the account I am using is a Global Admin.

Thanks and Warm Regards,


فريديريك ميندوزا
إداري أول، الاتصالات
الشركة الوطنية للضمان الصحي - ضمان
+971 56 687 3353        موبايل:
+971 2 614 9838 هاتف:
+971 2 614 5564 فاكس:
ص ب 128888 ابوظبي، الامارات العربية المتحدة     :العنوان
        [cid:15yearsLogo_93f3a0b3-6147-43a8-b9e7-52471648e0ed.png]
www.damanhealth.ae

Frederick Mendoza
Senior Administrator, Telecom
National Health Insurance Company - Daman
Mobile: +971 56 687 3353
Telephone:      +971 2 614 9838
Fax:    +971 2 614 5564
Address:        POB 128888, Abu Dhabi, UAE



[Logo 1]

 [Logo 1]                [Logo 1]

**Comment by MattWade-MS** [comment]
Are you able to get to CQD Web UI?  I believe the link is https://Cqd.teams.microsoft.com?  If yes, then the issue is with PBI.  I also see you are not signed into PBI (upper right hand corner).  Please make sure you are signed into PBI with a valid Azure AD account.  It doesn't have to be your admin account.

**Comment by Rahulgutal** [comment]
> We are getting an error when launching/syncing the QER dashboard
> 
> We have tested this on different PC's, different networks and with the updated QER versions.
> 
> We have raised this concern to Microsoft Premier Support but they have advised us to open this ticket from here as the template was provided from GitHub team.
> 
> ![QER Issue](https://user-images.githubusercontent.com/88764121/130055308-9c2bff04-a3de-4b5b-a1a6-c710e5804565.png)

You may Hit the close button and the Home page should load but you'll still see some errors on the top. Go to Query editor
Home Tab > queries section > Transform Data. It would open Power Query Editor.

On the left hand side in a column you see "DBIP" select that and again navigate to "Home Tab > Query Section > Advance Editor.

This would open the DBIP query page on this page you find a line "### Source = Web.Contents("https://download.db-ip.com/free/dbip-asn-lite-2021-07.csv.gz"),"

IN this line you need to change the date at the end of the line from "2021-07" to "2021-09" and click Done.

you'll now see data load in the query editor. Click "close & Load" first icon on the top left corner and now you'll see all starts to fall in place

**Comment by MattWade-MS** [comment]
Rahulgutal

Please make sure you are signed into Power BI (upper right hand corner).  Based on what I can see in the screenshot, it's the CQD query that's failing, not the DBIP query.  Please make sure you are signed in as PBI will use these credentials to validate access to the tenant.  If that account does not have CQD access you should get a popup asking you to authenticate with credentials that have CQD access.   To validate access try opening a browser and navigating to cqd.teams.microsoft.com.

I've also changed the DBIP URL in the latest release and also added notes in the **release notes and README file** for instruction on how to do this.  I recommend setting a remined monthly to update the URL.
