### ISSUE TITLE
db-ip.com 404 not found

### ISSUE THREAD

**Issue by rimroot** [MattWade-MS/QER#4]
When loading template getting 404 error from DBIP. It seems that file no longer exist. Previously it worked fine on the same computer.

![image](https://user-images.githubusercontent.com/29730129/133082724-79a029f8-b178-483a-9c06-d9fe5c1f8f50.png)

QER v4.4

**Comment by rimroot** [comment]
Found a workaround myself. Using Query Editor, modified DBIP URL to point to different file. Instead of "dbip-asn-lite-2021-**07**.csv.gz" changed to "dbip-asn-lite-2021-**08**.csv.gz". Not sure for how long it will work, but for now it is ok.

**Comment by dwhitney7** [comment]
@rimroot This is discussed in the release notes docx included in the zip download, but seems like you found the right way to address it. Consider setting a monthly reminder to update this, or review the option discussed in the release notes to set it to dynamic if you are using the QER report template solely in the PBI desktop client.
