### ISSUE TITLE
Media setup failures very low on Media Health tab, but high on Media Setup tab

### ISSUE THREAD

**Issue by jeff-frank-glic** [MattWade-MS/QER#6]
In QERPBI-v4.4.2, my media setup failures look low on the Media Health tab, they are high on the Media Setup tab.  Cross checking with CQD, I am having issues with call setup failures so something may not be right with the Media Health view.  This was working in QERPBI-v4.4.

**Comment by MattWade-MS** [comment]
Thank you Jeff.  I'll look into this.

**Comment by jeff-frank-glic** [comment]
I’m happy to provide some screen shots more directly if it would help, but I’d rather not post them publically.

Regards,

Jeff Frank
Director, Messaging Services
O: 610-807-6319  |  M: 484-714-5650
***@***.******@***.***>  |  guardianlife.com<https://guardianlife.com/>
[Guardian Logo]<https://www.guardianlife.com/>      [Guardian Facebook] <http://www.facebook.com/guardianlife/>   [Guardian LinkedIn] <https://www.linkedin.com/company/the-guardian-life-insurance-company-of-america_164085/>   [Guardian Twitter] <https://twitter.com/guardianlife>   [Guardian YouTube] <http://www.youtube.com/c/guardianlife?sub_confirmation=1>   ***@***.*** <https://www.instagram.com/guardianlife/>

**Comment by jeff-frank-glic** [comment]
Thanks!
