### ISSUE TITLE
QERPBI : city and building filters are limited to ~120 enties

### ISSUE THREAD

**Issue by fdeckert-soprasteria** [MattWade-MS/QER#8]
Our company has 124 cities and 188 buildings. yet on all tabs, only the first 113 cities and 131 buildings are listed

When we edit the report in powerbi web and powerbi desktop, when opening the 'citly' filter in the editor we notice that the first 113 are displayed quickly, then there is a long pause and the last 11 and loaded way later.

![qerpbi](https://user-images.githubusercontent.com/75070748/151955890-23c2c17e-4c0b-438e-a638-13826ec160f8.png)

**Comment by MattWade-MS** [comment]
This is a limitation of the slicer.  A slicer visual can only display 100 entries.  To select entries that do not show up, you can enable the search function by selecting the three dots while hovering over the slicer and selecting Search.  This will display a search bar (I try to enable these by default and will review them for the next release).  

The filter on the Filters pane will display more entries that the slicer.

**Comment by fdeckert-soprasteria** [comment]
thanks Matt. As a possible future evolution, would it be possible to have a 'Country' slicer, this way we can limit the number of cities to display.

**Comment by MattWade-MS** [comment]
All is possible.  Where would you like the Country filter?
