### ISSUE TITLE
How to filter out home networks

### ISSUE THREAD

**Issue by Petri-X** [MattWade-MS/QER#9]
Hi,

Tab: "Top 10 Network"

I tried to filter out the home networks with using "not start with 192.168." but that did not return anything back. Then I tried to use the following filters:
![image](https://user-images.githubusercontent.com/43988151/153009577-4a257463-d686-4219-a8ac-9d803aafcef1.png)
And as you can see, that did not excluded them.

So what would be the best way to filter out home networks?

**Comment by MattWade-MS** [comment]
Let me test this out for you Petri.  I might suggest changing the condition from _is not_ to _does not start with_.  I've had better luck when filtering subnets and ip addresses using these conditions.

**Comment by Petri-X** [comment]
That was good idea, but at least with this way I got only error :)

![image](https://user-images.githubusercontent.com/43988151/153394312-cb14ea58-97f4-4e31-9b21-dc55071d2e5d.png)

No matter if I selected AND/OR.

**Comment by MattWade-MS** [comment]
I played around with it a bit and you'll need a wildcard in the values.  This worked for me.  
![image](https://user-images.githubusercontent.com/34693246/153451648-523111e2-e27e-4a1f-85f6-8c990c3282ff.png)

**Comment by Petri-X** [comment]
Eh ! I would never been found it :) 
Big thanks !

And now AND/OR are also useless :D
![image](https://user-images.githubusercontent.com/43988151/153468682-d5c467b7-7587-49a5-afd8-e3649afbe3f2.png)
